# Server Settings (ServerProperties)
server:
  port: 8080
  address: localhost
  tomcat:
    # 解析含有中文名的文件的url
    uri-encoding: utf-8
    # 最大连接数
    max-connections: 1000
    # 最大线程数，即最大并发数。
    max-threads: 500
    # 最小备用线程数
    min-spare-threads: 20
    # 线程数达到maxThreads后，后续请求会被放入一个等待队列，acceptCount是这个队列的大小
    accept-count: 100
    # tomcat连接器
    connector: org.apache.coyote.http11.Http11NioProtocol
    # tomcat优化
    optimize: true
# Spring Settings
spring:
  # 指定静态资源处理路径，如果是默认/**，404请求不会抛出NoHandlerFoundException
  mvc:
    static-path-pattern: /static/**