package com.qi.backstage.model.domain;

import com.sfsctech.base.model.BaseDto;

public class BaseDictionary extends BaseDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dictionary.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dictionary.Guid
     *
     * @mbg.generated
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dictionary.GuidParent
     *
     * @mbg.generated
     */
    private String guidparent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dictionary.Name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dictionary.Content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dictionary.Description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dictionary.Sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dictionary.Status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dictionary.ID
     *
     * @return the value of base_dictionary.ID
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dictionary.ID
     *
     * @param id the value for base_dictionary.ID
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dictionary.Guid
     *
     * @return the value of base_dictionary.Guid
     * @mbg.generated
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dictionary.Guid
     *
     * @param guid the value for base_dictionary.Guid
     * @mbg.generated
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dictionary.GuidParent
     *
     * @return the value of base_dictionary.GuidParent
     * @mbg.generated
     */
    public String getGuidparent() {
        return guidparent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dictionary.GuidParent
     *
     * @param guidparent the value for base_dictionary.GuidParent
     * @mbg.generated
     */
    public void setGuidparent(String guidparent) {
        this.guidparent = guidparent == null ? null : guidparent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dictionary.Name
     *
     * @return the value of base_dictionary.Name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dictionary.Name
     *
     * @param name the value for base_dictionary.Name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dictionary.Content
     *
     * @return the value of base_dictionary.Content
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dictionary.Content
     *
     * @param content the value for base_dictionary.Content
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dictionary.Description
     *
     * @return the value of base_dictionary.Description
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dictionary.Description
     *
     * @param description the value for base_dictionary.Description
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dictionary.Sort
     *
     * @return the value of base_dictionary.Sort
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dictionary.Sort
     *
     * @param sort the value for base_dictionary.Sort
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dictionary.Status
     *
     * @return the value of base_dictionary.Status
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dictionary.Status
     *
     * @param status the value for base_dictionary.Status
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}