package com.qi.backstage.model.domain;

import java.util.ArrayList;
import java.util.List;

public class BaseMenuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    public BaseMenuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGuidIsNull() {
            addCriterion("Guid is null");
            return (Criteria) this;
        }

        public Criteria andGuidIsNotNull() {
            addCriterion("Guid is not null");
            return (Criteria) this;
        }

        public Criteria andGuidEqualTo(String value) {
            addCriterion("Guid =", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotEqualTo(String value) {
            addCriterion("Guid <>", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThan(String value) {
            addCriterion("Guid >", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidGreaterThanOrEqualTo(String value) {
            addCriterion("Guid >=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThan(String value) {
            addCriterion("Guid <", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLessThanOrEqualTo(String value) {
            addCriterion("Guid <=", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidLike(String value) {
            addCriterion("Guid like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotLike(String value) {
            addCriterion("Guid not like", value, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidIn(List<String> values) {
            addCriterion("Guid in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotIn(List<String> values) {
            addCriterion("Guid not in", values, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidBetween(String value1, String value2) {
            addCriterion("Guid between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidNotBetween(String value1, String value2) {
            addCriterion("Guid not between", value1, value2, "guid");
            return (Criteria) this;
        }

        public Criteria andGuidparentIsNull() {
            addCriterion("GuidParent is null");
            return (Criteria) this;
        }

        public Criteria andGuidparentIsNotNull() {
            addCriterion("GuidParent is not null");
            return (Criteria) this;
        }

        public Criteria andGuidparentEqualTo(String value) {
            addCriterion("GuidParent =", value, "guidparent");
            return (Criteria) this;
        }

        public Criteria andGuidparentNotEqualTo(String value) {
            addCriterion("GuidParent <>", value, "guidparent");
            return (Criteria) this;
        }

        public Criteria andGuidparentGreaterThan(String value) {
            addCriterion("GuidParent >", value, "guidparent");
            return (Criteria) this;
        }

        public Criteria andGuidparentGreaterThanOrEqualTo(String value) {
            addCriterion("GuidParent >=", value, "guidparent");
            return (Criteria) this;
        }

        public Criteria andGuidparentLessThan(String value) {
            addCriterion("GuidParent <", value, "guidparent");
            return (Criteria) this;
        }

        public Criteria andGuidparentLessThanOrEqualTo(String value) {
            addCriterion("GuidParent <=", value, "guidparent");
            return (Criteria) this;
        }

        public Criteria andGuidparentLike(String value) {
            addCriterion("GuidParent like", value, "guidparent");
            return (Criteria) this;
        }

        public Criteria andGuidparentNotLike(String value) {
            addCriterion("GuidParent not like", value, "guidparent");
            return (Criteria) this;
        }

        public Criteria andGuidparentIn(List<String> values) {
            addCriterion("GuidParent in", values, "guidparent");
            return (Criteria) this;
        }

        public Criteria andGuidparentNotIn(List<String> values) {
            addCriterion("GuidParent not in", values, "guidparent");
            return (Criteria) this;
        }

        public Criteria andGuidparentBetween(String value1, String value2) {
            addCriterion("GuidParent between", value1, value2, "guidparent");
            return (Criteria) this;
        }

        public Criteria andGuidparentNotBetween(String value1, String value2) {
            addCriterion("GuidParent not between", value1, value2, "guidparent");
            return (Criteria) this;
        }

        public Criteria andGuidrootIsNull() {
            addCriterion("GuidRoot is null");
            return (Criteria) this;
        }

        public Criteria andGuidrootIsNotNull() {
            addCriterion("GuidRoot is not null");
            return (Criteria) this;
        }

        public Criteria andGuidrootEqualTo(String value) {
            addCriterion("GuidRoot =", value, "guidroot");
            return (Criteria) this;
        }

        public Criteria andGuidrootNotEqualTo(String value) {
            addCriterion("GuidRoot <>", value, "guidroot");
            return (Criteria) this;
        }

        public Criteria andGuidrootGreaterThan(String value) {
            addCriterion("GuidRoot >", value, "guidroot");
            return (Criteria) this;
        }

        public Criteria andGuidrootGreaterThanOrEqualTo(String value) {
            addCriterion("GuidRoot >=", value, "guidroot");
            return (Criteria) this;
        }

        public Criteria andGuidrootLessThan(String value) {
            addCriterion("GuidRoot <", value, "guidroot");
            return (Criteria) this;
        }

        public Criteria andGuidrootLessThanOrEqualTo(String value) {
            addCriterion("GuidRoot <=", value, "guidroot");
            return (Criteria) this;
        }

        public Criteria andGuidrootLike(String value) {
            addCriterion("GuidRoot like", value, "guidroot");
            return (Criteria) this;
        }

        public Criteria andGuidrootNotLike(String value) {
            addCriterion("GuidRoot not like", value, "guidroot");
            return (Criteria) this;
        }

        public Criteria andGuidrootIn(List<String> values) {
            addCriterion("GuidRoot in", values, "guidroot");
            return (Criteria) this;
        }

        public Criteria andGuidrootNotIn(List<String> values) {
            addCriterion("GuidRoot not in", values, "guidroot");
            return (Criteria) this;
        }

        public Criteria andGuidrootBetween(String value1, String value2) {
            addCriterion("GuidRoot between", value1, value2, "guidroot");
            return (Criteria) this;
        }

        public Criteria andGuidrootNotBetween(String value1, String value2) {
            addCriterion("GuidRoot not between", value1, value2, "guidroot");
            return (Criteria) this;
        }

        public Criteria andCodesystemIsNull() {
            addCriterion("CodeSystem is null");
            return (Criteria) this;
        }

        public Criteria andCodesystemIsNotNull() {
            addCriterion("CodeSystem is not null");
            return (Criteria) this;
        }

        public Criteria andCodesystemEqualTo(String value) {
            addCriterion("CodeSystem =", value, "codesystem");
            return (Criteria) this;
        }

        public Criteria andCodesystemNotEqualTo(String value) {
            addCriterion("CodeSystem <>", value, "codesystem");
            return (Criteria) this;
        }

        public Criteria andCodesystemGreaterThan(String value) {
            addCriterion("CodeSystem >", value, "codesystem");
            return (Criteria) this;
        }

        public Criteria andCodesystemGreaterThanOrEqualTo(String value) {
            addCriterion("CodeSystem >=", value, "codesystem");
            return (Criteria) this;
        }

        public Criteria andCodesystemLessThan(String value) {
            addCriterion("CodeSystem <", value, "codesystem");
            return (Criteria) this;
        }

        public Criteria andCodesystemLessThanOrEqualTo(String value) {
            addCriterion("CodeSystem <=", value, "codesystem");
            return (Criteria) this;
        }

        public Criteria andCodesystemLike(String value) {
            addCriterion("CodeSystem like", value, "codesystem");
            return (Criteria) this;
        }

        public Criteria andCodesystemNotLike(String value) {
            addCriterion("CodeSystem not like", value, "codesystem");
            return (Criteria) this;
        }

        public Criteria andCodesystemIn(List<String> values) {
            addCriterion("CodeSystem in", values, "codesystem");
            return (Criteria) this;
        }

        public Criteria andCodesystemNotIn(List<String> values) {
            addCriterion("CodeSystem not in", values, "codesystem");
            return (Criteria) this;
        }

        public Criteria andCodesystemBetween(String value1, String value2) {
            addCriterion("CodeSystem between", value1, value2, "codesystem");
            return (Criteria) this;
        }

        public Criteria andCodesystemNotBetween(String value1, String value2) {
            addCriterion("CodeSystem not between", value1, value2, "codesystem");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("Code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("Code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("Code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("Code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("Code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("Code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("Code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("Code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("Code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("Code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("Code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("Code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("Code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("Code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andNameparentIsNull() {
            addCriterion("NameParent is null");
            return (Criteria) this;
        }

        public Criteria andNameparentIsNotNull() {
            addCriterion("NameParent is not null");
            return (Criteria) this;
        }

        public Criteria andNameparentEqualTo(String value) {
            addCriterion("NameParent =", value, "nameparent");
            return (Criteria) this;
        }

        public Criteria andNameparentNotEqualTo(String value) {
            addCriterion("NameParent <>", value, "nameparent");
            return (Criteria) this;
        }

        public Criteria andNameparentGreaterThan(String value) {
            addCriterion("NameParent >", value, "nameparent");
            return (Criteria) this;
        }

        public Criteria andNameparentGreaterThanOrEqualTo(String value) {
            addCriterion("NameParent >=", value, "nameparent");
            return (Criteria) this;
        }

        public Criteria andNameparentLessThan(String value) {
            addCriterion("NameParent <", value, "nameparent");
            return (Criteria) this;
        }

        public Criteria andNameparentLessThanOrEqualTo(String value) {
            addCriterion("NameParent <=", value, "nameparent");
            return (Criteria) this;
        }

        public Criteria andNameparentLike(String value) {
            addCriterion("NameParent like", value, "nameparent");
            return (Criteria) this;
        }

        public Criteria andNameparentNotLike(String value) {
            addCriterion("NameParent not like", value, "nameparent");
            return (Criteria) this;
        }

        public Criteria andNameparentIn(List<String> values) {
            addCriterion("NameParent in", values, "nameparent");
            return (Criteria) this;
        }

        public Criteria andNameparentNotIn(List<String> values) {
            addCriterion("NameParent not in", values, "nameparent");
            return (Criteria) this;
        }

        public Criteria andNameparentBetween(String value1, String value2) {
            addCriterion("NameParent between", value1, value2, "nameparent");
            return (Criteria) this;
        }

        public Criteria andNameparentNotBetween(String value1, String value2) {
            addCriterion("NameParent not between", value1, value2, "nameparent");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("Name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("Name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("Name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("Name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("Name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("Name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("Name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("Name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("Name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("Name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("Name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("Name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("Name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("Name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andContextpathIsNull() {
            addCriterion("ContextPath is null");
            return (Criteria) this;
        }

        public Criteria andContextpathIsNotNull() {
            addCriterion("ContextPath is not null");
            return (Criteria) this;
        }

        public Criteria andContextpathEqualTo(String value) {
            addCriterion("ContextPath =", value, "contextpath");
            return (Criteria) this;
        }

        public Criteria andContextpathNotEqualTo(String value) {
            addCriterion("ContextPath <>", value, "contextpath");
            return (Criteria) this;
        }

        public Criteria andContextpathGreaterThan(String value) {
            addCriterion("ContextPath >", value, "contextpath");
            return (Criteria) this;
        }

        public Criteria andContextpathGreaterThanOrEqualTo(String value) {
            addCriterion("ContextPath >=", value, "contextpath");
            return (Criteria) this;
        }

        public Criteria andContextpathLessThan(String value) {
            addCriterion("ContextPath <", value, "contextpath");
            return (Criteria) this;
        }

        public Criteria andContextpathLessThanOrEqualTo(String value) {
            addCriterion("ContextPath <=", value, "contextpath");
            return (Criteria) this;
        }

        public Criteria andContextpathLike(String value) {
            addCriterion("ContextPath like", value, "contextpath");
            return (Criteria) this;
        }

        public Criteria andContextpathNotLike(String value) {
            addCriterion("ContextPath not like", value, "contextpath");
            return (Criteria) this;
        }

        public Criteria andContextpathIn(List<String> values) {
            addCriterion("ContextPath in", values, "contextpath");
            return (Criteria) this;
        }

        public Criteria andContextpathNotIn(List<String> values) {
            addCriterion("ContextPath not in", values, "contextpath");
            return (Criteria) this;
        }

        public Criteria andContextpathBetween(String value1, String value2) {
            addCriterion("ContextPath between", value1, value2, "contextpath");
            return (Criteria) this;
        }

        public Criteria andContextpathNotBetween(String value1, String value2) {
            addCriterion("ContextPath not between", value1, value2, "contextpath");
            return (Criteria) this;
        }

        public Criteria andControllerIsNull() {
            addCriterion("Controller is null");
            return (Criteria) this;
        }

        public Criteria andControllerIsNotNull() {
            addCriterion("Controller is not null");
            return (Criteria) this;
        }

        public Criteria andControllerEqualTo(String value) {
            addCriterion("Controller =", value, "controller");
            return (Criteria) this;
        }

        public Criteria andControllerNotEqualTo(String value) {
            addCriterion("Controller <>", value, "controller");
            return (Criteria) this;
        }

        public Criteria andControllerGreaterThan(String value) {
            addCriterion("Controller >", value, "controller");
            return (Criteria) this;
        }

        public Criteria andControllerGreaterThanOrEqualTo(String value) {
            addCriterion("Controller >=", value, "controller");
            return (Criteria) this;
        }

        public Criteria andControllerLessThan(String value) {
            addCriterion("Controller <", value, "controller");
            return (Criteria) this;
        }

        public Criteria andControllerLessThanOrEqualTo(String value) {
            addCriterion("Controller <=", value, "controller");
            return (Criteria) this;
        }

        public Criteria andControllerLike(String value) {
            addCriterion("Controller like", value, "controller");
            return (Criteria) this;
        }

        public Criteria andControllerNotLike(String value) {
            addCriterion("Controller not like", value, "controller");
            return (Criteria) this;
        }

        public Criteria andControllerIn(List<String> values) {
            addCriterion("Controller in", values, "controller");
            return (Criteria) this;
        }

        public Criteria andControllerNotIn(List<String> values) {
            addCriterion("Controller not in", values, "controller");
            return (Criteria) this;
        }

        public Criteria andControllerBetween(String value1, String value2) {
            addCriterion("Controller between", value1, value2, "controller");
            return (Criteria) this;
        }

        public Criteria andControllerNotBetween(String value1, String value2) {
            addCriterion("Controller not between", value1, value2, "controller");
            return (Criteria) this;
        }

        public Criteria andMappingIsNull() {
            addCriterion("Mapping is null");
            return (Criteria) this;
        }

        public Criteria andMappingIsNotNull() {
            addCriterion("Mapping is not null");
            return (Criteria) this;
        }

        public Criteria andMappingEqualTo(String value) {
            addCriterion("Mapping =", value, "mapping");
            return (Criteria) this;
        }

        public Criteria andMappingNotEqualTo(String value) {
            addCriterion("Mapping <>", value, "mapping");
            return (Criteria) this;
        }

        public Criteria andMappingGreaterThan(String value) {
            addCriterion("Mapping >", value, "mapping");
            return (Criteria) this;
        }

        public Criteria andMappingGreaterThanOrEqualTo(String value) {
            addCriterion("Mapping >=", value, "mapping");
            return (Criteria) this;
        }

        public Criteria andMappingLessThan(String value) {
            addCriterion("Mapping <", value, "mapping");
            return (Criteria) this;
        }

        public Criteria andMappingLessThanOrEqualTo(String value) {
            addCriterion("Mapping <=", value, "mapping");
            return (Criteria) this;
        }

        public Criteria andMappingLike(String value) {
            addCriterion("Mapping like", value, "mapping");
            return (Criteria) this;
        }

        public Criteria andMappingNotLike(String value) {
            addCriterion("Mapping not like", value, "mapping");
            return (Criteria) this;
        }

        public Criteria andMappingIn(List<String> values) {
            addCriterion("Mapping in", values, "mapping");
            return (Criteria) this;
        }

        public Criteria andMappingNotIn(List<String> values) {
            addCriterion("Mapping not in", values, "mapping");
            return (Criteria) this;
        }

        public Criteria andMappingBetween(String value1, String value2) {
            addCriterion("Mapping between", value1, value2, "mapping");
            return (Criteria) this;
        }

        public Criteria andMappingNotBetween(String value1, String value2) {
            addCriterion("Mapping not between", value1, value2, "mapping");
            return (Criteria) this;
        }

        public Criteria andIconpathIsNull() {
            addCriterion("IconPath is null");
            return (Criteria) this;
        }

        public Criteria andIconpathIsNotNull() {
            addCriterion("IconPath is not null");
            return (Criteria) this;
        }

        public Criteria andIconpathEqualTo(String value) {
            addCriterion("IconPath =", value, "iconpath");
            return (Criteria) this;
        }

        public Criteria andIconpathNotEqualTo(String value) {
            addCriterion("IconPath <>", value, "iconpath");
            return (Criteria) this;
        }

        public Criteria andIconpathGreaterThan(String value) {
            addCriterion("IconPath >", value, "iconpath");
            return (Criteria) this;
        }

        public Criteria andIconpathGreaterThanOrEqualTo(String value) {
            addCriterion("IconPath >=", value, "iconpath");
            return (Criteria) this;
        }

        public Criteria andIconpathLessThan(String value) {
            addCriterion("IconPath <", value, "iconpath");
            return (Criteria) this;
        }

        public Criteria andIconpathLessThanOrEqualTo(String value) {
            addCriterion("IconPath <=", value, "iconpath");
            return (Criteria) this;
        }

        public Criteria andIconpathLike(String value) {
            addCriterion("IconPath like", value, "iconpath");
            return (Criteria) this;
        }

        public Criteria andIconpathNotLike(String value) {
            addCriterion("IconPath not like", value, "iconpath");
            return (Criteria) this;
        }

        public Criteria andIconpathIn(List<String> values) {
            addCriterion("IconPath in", values, "iconpath");
            return (Criteria) this;
        }

        public Criteria andIconpathNotIn(List<String> values) {
            addCriterion("IconPath not in", values, "iconpath");
            return (Criteria) this;
        }

        public Criteria andIconpathBetween(String value1, String value2) {
            addCriterion("IconPath between", value1, value2, "iconpath");
            return (Criteria) this;
        }

        public Criteria andIconpathNotBetween(String value1, String value2) {
            addCriterion("IconPath not between", value1, value2, "iconpath");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("Description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("Description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("Description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("Description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("Description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("Description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("Description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("Description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("Description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("Description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("Description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("Description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("Description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("Description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("Level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("Level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(Integer value) {
            addCriterion("Level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(Integer value) {
            addCriterion("Level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(Integer value) {
            addCriterion("Level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("Level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(Integer value) {
            addCriterion("Level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(Integer value) {
            addCriterion("Level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<Integer> values) {
            addCriterion("Level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<Integer> values) {
            addCriterion("Level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(Integer value1, Integer value2) {
            addCriterion("Level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("Level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andSortIsNull() {
            addCriterion("Sort is null");
            return (Criteria) this;
        }

        public Criteria andSortIsNotNull() {
            addCriterion("Sort is not null");
            return (Criteria) this;
        }

        public Criteria andSortEqualTo(Integer value) {
            addCriterion("Sort =", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotEqualTo(Integer value) {
            addCriterion("Sort <>", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThan(Integer value) {
            addCriterion("Sort >", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("Sort >=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThan(Integer value) {
            addCriterion("Sort <", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThanOrEqualTo(Integer value) {
            addCriterion("Sort <=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortIn(List<Integer> values) {
            addCriterion("Sort in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotIn(List<Integer> values) {
            addCriterion("Sort not in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortBetween(Integer value1, Integer value2) {
            addCriterion("Sort between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotBetween(Integer value1, Integer value2) {
            addCriterion("Sort not between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andIsleafIsNull() {
            addCriterion("IsLeaf is null");
            return (Criteria) this;
        }

        public Criteria andIsleafIsNotNull() {
            addCriterion("IsLeaf is not null");
            return (Criteria) this;
        }

        public Criteria andIsleafEqualTo(Boolean value) {
            addCriterion("IsLeaf =", value, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafNotEqualTo(Boolean value) {
            addCriterion("IsLeaf <>", value, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafGreaterThan(Boolean value) {
            addCriterion("IsLeaf >", value, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IsLeaf >=", value, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafLessThan(Boolean value) {
            addCriterion("IsLeaf <", value, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafLessThanOrEqualTo(Boolean value) {
            addCriterion("IsLeaf <=", value, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafIn(List<Boolean> values) {
            addCriterion("IsLeaf in", values, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafNotIn(List<Boolean> values) {
            addCriterion("IsLeaf not in", values, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafBetween(Boolean value1, Boolean value2) {
            addCriterion("IsLeaf between", value1, value2, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IsLeaf not between", value1, value2, "isleaf");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("Status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("Status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Boolean value) {
            addCriterion("Status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Boolean value) {
            addCriterion("Status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Boolean value) {
            addCriterion("Status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("Status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Boolean value) {
            addCriterion("Status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("Status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Boolean> values) {
            addCriterion("Status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Boolean> values) {
            addCriterion("Status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("Status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("Status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table base_menu
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table base_menu
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}