package com.qi.management.model.domain;

public class TBaseSystem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_System.Guid
     *
     * @mbg.generated
     */
    private Long guid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_System.Code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_System.NameCn
     *
     * @mbg.generated
     */
    private String namecn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_System.NameEn
     *
     * @mbg.generated
     */
    private String nameen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_System.Domain
     *
     * @mbg.generated
     */
    private String domain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_System.ContextPath
     *
     * @mbg.generated
     */
    private String contextpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_System.HomePage
     *
     * @mbg.generated
     */
    private String homepage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_System.Type
     *
     * @mbg.generated
     */
    private Short type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_System.LogoPath
     *
     * @mbg.generated
     */
    private String logopath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_System.Status
     *
     * @mbg.generated
     */
    private Short status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_System.Guid
     *
     * @return the value of T_Base_System.Guid
     *
     * @mbg.generated
     */
    public Long getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_System.Guid
     *
     * @param guid the value for T_Base_System.Guid
     *
     * @mbg.generated
     */
    public void setGuid(Long guid) {
        this.guid = guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_System.Code
     *
     * @return the value of T_Base_System.Code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_System.Code
     *
     * @param code the value for T_Base_System.Code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_System.NameCn
     *
     * @return the value of T_Base_System.NameCn
     *
     * @mbg.generated
     */
    public String getNamecn() {
        return namecn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_System.NameCn
     *
     * @param namecn the value for T_Base_System.NameCn
     *
     * @mbg.generated
     */
    public void setNamecn(String namecn) {
        this.namecn = namecn == null ? null : namecn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_System.NameEn
     *
     * @return the value of T_Base_System.NameEn
     *
     * @mbg.generated
     */
    public String getNameen() {
        return nameen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_System.NameEn
     *
     * @param nameen the value for T_Base_System.NameEn
     *
     * @mbg.generated
     */
    public void setNameen(String nameen) {
        this.nameen = nameen == null ? null : nameen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_System.Domain
     *
     * @return the value of T_Base_System.Domain
     *
     * @mbg.generated
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_System.Domain
     *
     * @param domain the value for T_Base_System.Domain
     *
     * @mbg.generated
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_System.ContextPath
     *
     * @return the value of T_Base_System.ContextPath
     *
     * @mbg.generated
     */
    public String getContextpath() {
        return contextpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_System.ContextPath
     *
     * @param contextpath the value for T_Base_System.ContextPath
     *
     * @mbg.generated
     */
    public void setContextpath(String contextpath) {
        this.contextpath = contextpath == null ? null : contextpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_System.HomePage
     *
     * @return the value of T_Base_System.HomePage
     *
     * @mbg.generated
     */
    public String getHomepage() {
        return homepage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_System.HomePage
     *
     * @param homepage the value for T_Base_System.HomePage
     *
     * @mbg.generated
     */
    public void setHomepage(String homepage) {
        this.homepage = homepage == null ? null : homepage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_System.Type
     *
     * @return the value of T_Base_System.Type
     *
     * @mbg.generated
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_System.Type
     *
     * @param type the value for T_Base_System.Type
     *
     * @mbg.generated
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_System.LogoPath
     *
     * @return the value of T_Base_System.LogoPath
     *
     * @mbg.generated
     */
    public String getLogopath() {
        return logopath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_System.LogoPath
     *
     * @param logopath the value for T_Base_System.LogoPath
     *
     * @mbg.generated
     */
    public void setLogopath(String logopath) {
        this.logopath = logopath == null ? null : logopath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_System.Status
     *
     * @return the value of T_Base_System.Status
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_System.Status
     *
     * @param status the value for T_Base_System.Status
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }
}