package com.qi.management.model.domain;

public class TBaseDictionary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_Dictionary.Guid
     *
     * @mbg.generated
     */
    private Long guid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_Dictionary.ParentCode
     *
     * @mbg.generated
     */
    private String parentcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_Dictionary.DictCode
     *
     * @mbg.generated
     */
    private String dictcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_Dictionary.DictName
     *
     * @mbg.generated
     */
    private String dictname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_Dictionary.Description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_Dictionary.Sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_Dictionary.Status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_Dictionary.Guid
     *
     * @return the value of T_Base_Dictionary.Guid
     *
     * @mbg.generated
     */
    public Long getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_Dictionary.Guid
     *
     * @param guid the value for T_Base_Dictionary.Guid
     *
     * @mbg.generated
     */
    public void setGuid(Long guid) {
        this.guid = guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_Dictionary.ParentCode
     *
     * @return the value of T_Base_Dictionary.ParentCode
     *
     * @mbg.generated
     */
    public String getParentcode() {
        return parentcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_Dictionary.ParentCode
     *
     * @param parentcode the value for T_Base_Dictionary.ParentCode
     *
     * @mbg.generated
     */
    public void setParentcode(String parentcode) {
        this.parentcode = parentcode == null ? null : parentcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_Dictionary.DictCode
     *
     * @return the value of T_Base_Dictionary.DictCode
     *
     * @mbg.generated
     */
    public String getDictcode() {
        return dictcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_Dictionary.DictCode
     *
     * @param dictcode the value for T_Base_Dictionary.DictCode
     *
     * @mbg.generated
     */
    public void setDictcode(String dictcode) {
        this.dictcode = dictcode == null ? null : dictcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_Dictionary.DictName
     *
     * @return the value of T_Base_Dictionary.DictName
     *
     * @mbg.generated
     */
    public String getDictname() {
        return dictname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_Dictionary.DictName
     *
     * @param dictname the value for T_Base_Dictionary.DictName
     *
     * @mbg.generated
     */
    public void setDictname(String dictname) {
        this.dictname = dictname == null ? null : dictname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_Dictionary.Description
     *
     * @return the value of T_Base_Dictionary.Description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_Dictionary.Description
     *
     * @param description the value for T_Base_Dictionary.Description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_Dictionary.Sort
     *
     * @return the value of T_Base_Dictionary.Sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_Dictionary.Sort
     *
     * @param sort the value for T_Base_Dictionary.Sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_Dictionary.Status
     *
     * @return the value of T_Base_Dictionary.Status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_Dictionary.Status
     *
     * @param status the value for T_Base_Dictionary.Status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}