package com.qi.management.model.domain;

public class TBaseMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_Menu.Guid
     *
     * @mbg.generated
     */
    private Long guid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_Menu.ParentID
     *
     * @mbg.generated
     */
    private Long parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_Menu.ParentName
     *
     * @mbg.generated
     */
    private String parentname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_Menu.SystemCode
     *
     * @mbg.generated
     */
    private String systemcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_Menu.MenuCode
     *
     * @mbg.generated
     */
    private String menucode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_Menu.MenuName
     *
     * @mbg.generated
     */
    private String menuname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_Menu.ContextPath
     *
     * @mbg.generated
     */
    private String contextpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_Menu.Controller
     *
     * @mbg.generated
     */
    private String controller;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_Menu.RequestMapping
     *
     * @mbg.generated
     */
    private String requestmapping;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_Menu.IconPath
     *
     * @mbg.generated
     */
    private String iconpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_Menu.Description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_Menu.RootID
     *
     * @mbg.generated
     */
    private Long rootid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_Menu.Level
     *
     * @mbg.generated
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_Menu.Sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_Menu.IsLeaf
     *
     * @mbg.generated
     */
    private Boolean isleaf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Base_Menu.Status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_Menu.Guid
     *
     * @return the value of T_Base_Menu.Guid
     *
     * @mbg.generated
     */
    public Long getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_Menu.Guid
     *
     * @param guid the value for T_Base_Menu.Guid
     *
     * @mbg.generated
     */
    public void setGuid(Long guid) {
        this.guid = guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_Menu.ParentID
     *
     * @return the value of T_Base_Menu.ParentID
     *
     * @mbg.generated
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_Menu.ParentID
     *
     * @param parentid the value for T_Base_Menu.ParentID
     *
     * @mbg.generated
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_Menu.ParentName
     *
     * @return the value of T_Base_Menu.ParentName
     *
     * @mbg.generated
     */
    public String getParentname() {
        return parentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_Menu.ParentName
     *
     * @param parentname the value for T_Base_Menu.ParentName
     *
     * @mbg.generated
     */
    public void setParentname(String parentname) {
        this.parentname = parentname == null ? null : parentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_Menu.SystemCode
     *
     * @return the value of T_Base_Menu.SystemCode
     *
     * @mbg.generated
     */
    public String getSystemcode() {
        return systemcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_Menu.SystemCode
     *
     * @param systemcode the value for T_Base_Menu.SystemCode
     *
     * @mbg.generated
     */
    public void setSystemcode(String systemcode) {
        this.systemcode = systemcode == null ? null : systemcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_Menu.MenuCode
     *
     * @return the value of T_Base_Menu.MenuCode
     *
     * @mbg.generated
     */
    public String getMenucode() {
        return menucode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_Menu.MenuCode
     *
     * @param menucode the value for T_Base_Menu.MenuCode
     *
     * @mbg.generated
     */
    public void setMenucode(String menucode) {
        this.menucode = menucode == null ? null : menucode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_Menu.MenuName
     *
     * @return the value of T_Base_Menu.MenuName
     *
     * @mbg.generated
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_Menu.MenuName
     *
     * @param menuname the value for T_Base_Menu.MenuName
     *
     * @mbg.generated
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname == null ? null : menuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_Menu.ContextPath
     *
     * @return the value of T_Base_Menu.ContextPath
     *
     * @mbg.generated
     */
    public String getContextpath() {
        return contextpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_Menu.ContextPath
     *
     * @param contextpath the value for T_Base_Menu.ContextPath
     *
     * @mbg.generated
     */
    public void setContextpath(String contextpath) {
        this.contextpath = contextpath == null ? null : contextpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_Menu.Controller
     *
     * @return the value of T_Base_Menu.Controller
     *
     * @mbg.generated
     */
    public String getController() {
        return controller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_Menu.Controller
     *
     * @param controller the value for T_Base_Menu.Controller
     *
     * @mbg.generated
     */
    public void setController(String controller) {
        this.controller = controller == null ? null : controller.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_Menu.RequestMapping
     *
     * @return the value of T_Base_Menu.RequestMapping
     *
     * @mbg.generated
     */
    public String getRequestmapping() {
        return requestmapping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_Menu.RequestMapping
     *
     * @param requestmapping the value for T_Base_Menu.RequestMapping
     *
     * @mbg.generated
     */
    public void setRequestmapping(String requestmapping) {
        this.requestmapping = requestmapping == null ? null : requestmapping.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_Menu.IconPath
     *
     * @return the value of T_Base_Menu.IconPath
     *
     * @mbg.generated
     */
    public String getIconpath() {
        return iconpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_Menu.IconPath
     *
     * @param iconpath the value for T_Base_Menu.IconPath
     *
     * @mbg.generated
     */
    public void setIconpath(String iconpath) {
        this.iconpath = iconpath == null ? null : iconpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_Menu.Description
     *
     * @return the value of T_Base_Menu.Description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_Menu.Description
     *
     * @param description the value for T_Base_Menu.Description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_Menu.RootID
     *
     * @return the value of T_Base_Menu.RootID
     *
     * @mbg.generated
     */
    public Long getRootid() {
        return rootid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_Menu.RootID
     *
     * @param rootid the value for T_Base_Menu.RootID
     *
     * @mbg.generated
     */
    public void setRootid(Long rootid) {
        this.rootid = rootid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_Menu.Level
     *
     * @return the value of T_Base_Menu.Level
     *
     * @mbg.generated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_Menu.Level
     *
     * @param level the value for T_Base_Menu.Level
     *
     * @mbg.generated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_Menu.Sort
     *
     * @return the value of T_Base_Menu.Sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_Menu.Sort
     *
     * @param sort the value for T_Base_Menu.Sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_Menu.IsLeaf
     *
     * @return the value of T_Base_Menu.IsLeaf
     *
     * @mbg.generated
     */
    public Boolean getIsleaf() {
        return isleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_Menu.IsLeaf
     *
     * @param isleaf the value for T_Base_Menu.IsLeaf
     *
     * @mbg.generated
     */
    public void setIsleaf(Boolean isleaf) {
        this.isleaf = isleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Base_Menu.Status
     *
     * @return the value of T_Base_Menu.Status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Base_Menu.Status
     *
     * @param status the value for T_Base_Menu.Status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}