#server setting
server:
  port: 8102
  address: localhost
  context-path: /sso-server
  tomcat:
    # 解析含有中文名的文件的url
    uri-encoding: utf-8
    # 最大连接数
    max-connections: 1000
    # 最大线程数，即最大并发数。
    max-threads: 500
    # 最小备用线程数
    min-spare-threads: 20
    # 线程数达到maxThreads后，后续请求会被放入一个等待队列，acceptCount是这个队列的大小
    accept-count: 100
    # tomcat连接器
    connector: org.apache.coyote.http11.Http11NioProtocol
    # tomcat优化
    optimize: true
#  context-parameters:
#    logback-config-location: http://localhost:8888/logback/framework/thymeleaf
#    logback-expose-webapp-root: true
cache:
  redis:
    host: 172.16.225.98
    port: 6379
    password: redis123
    pool:
      max-active: 300
      max-wait: 10000
      max-idle: 100
      min-idle: 50
#dubbo setting
dubbo:
  application:
    # 服务提供者名称信息
    name: SSO-Server
    # 日志适配
    logger: slf4j
  registry:
    protocol: zookeeper
    # zookeeper注册中心服务地址
    address: 172.16.225.98:2181
    # 注册中心不存在时，是否报错
    check: true
    # 是否向此注册中心注册服务，如果设为false，将只订阅，不注册
    register: true
    # 是否向此注册中心订阅服务，如果设为false，将只注册，不订阅
    subscribe: true
    # 注册中心请求超时时间(毫秒)
    timeout: 2000
  protocol:
    optimizer: Kryo
    config: Single
    single:
      port: 20890
      name: dubbo
  rpc:
    service-package: com.qi.sso.server.rpc
#common setting
website:
  sso:
    jwt:
      subject: Single Sign-on
      issuer: SSO-Server
      expiration: 1800000