#server setting
server:
  port: 8102
  tomcat:
    # 解析含有中文名的文件的url
    uri-encoding: utf-8
    # 最大连接数
    max-connections: 1000
    # 最大线程数，即最大并发数。
    max-threads: 500
    # 最小备用线程数
    min-spare-threads: 20
    # 线程数达到maxThreads后，后续请求会被放入一个等待队列，acceptCount是这个队列的大小
    accept-count: 100
    # tomcat连接器
    connector: org.apache.coyote.http11.Http11NioProtocol
    # tomcat优化
    optimize: true
#  context-parameters:
#    logback-config-location: http://localhost:8888/logback/framework/thymeleaf
#    logback-expose-webapp-root: true
eureka:
  client:
    # 向注册中心注册
    fetch-registry: true
    # 服务清单的缓存更新时间，默认30秒一次
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:10002/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 没有心跳的淘汰时间，10秒，即服务续约到期时间（缺省为90s）
    hostname: ${eureka.instance.ip-address}
    instance-id: ${eureka.instance.ip-address}:${server.port}
    prefer-ip-address: true
    ip-address: localhost
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
#spring setting
spring:
  application:
    name: sso-server
  boot:
    admin:
      client:
        url: "http://${eureka.instance.ip-address}:10001"
  redis:
    password: 3936796F7636592D2D4D552E
    jedis:
      pool:
        max-active: 300
        max-wait: 10s
        max-idle: 100
        min-idle: 50
    cluster:
      max-redirects: 3
      nodes:
        - 172.16.229.204:6001
        - 172.16.229.204:6002
        - 172.16.229.204:6003
        - 172.16.229.204:6004
        - 172.16.229.204:6005
        - 172.16.229.204:6006
#common setting
website:
  sso:
    jwt:
      subject: Single Sign-on
      issuer: QI-SSO
      expiration: 1800000