eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10002/eureka/
server:
  port: 8000
spring:
  application:
    name: api-basic
zuul:
  routes:
    platform:
      path: /platform/**
      serviceId: platform-backend
    dictionary:
      path: /dictionary/**
      serviceId: dictionary-controller
    dictionary:
      path: /management/**
      serviceId: management-controller