package com.qi.management.mapper;

import com.qi.management.model.domain.TBaseSystem;
import com.qi.management.model.domain.TBaseSystemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBaseSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_System
     *
     * @mbg.generated
     */
    long countByExample(TBaseSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_System
     *
     * @mbg.generated
     */
    int deleteByExample(TBaseSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_System
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_System
     *
     * @mbg.generated
     */
    int insert(TBaseSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_System
     *
     * @mbg.generated
     */
    int insertSelective(TBaseSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_System
     *
     * @mbg.generated
     */
    List<TBaseSystem> selectByExample(TBaseSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_System
     *
     * @mbg.generated
     */
    TBaseSystem selectByPrimaryKey(Long guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_System
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TBaseSystem record, @Param("example") TBaseSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_System
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TBaseSystem record, @Param("example") TBaseSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_System
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TBaseSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_System
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TBaseSystem record);
}