package com.qi.management.mapper;

import com.qi.management.model.domain.TBaseMenu;
import com.qi.management.model.domain.TBaseMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBaseMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_Menu
     *
     * @mbg.generated
     */
    long countByExample(TBaseMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_Menu
     *
     * @mbg.generated
     */
    int deleteByExample(TBaseMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_Menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_Menu
     *
     * @mbg.generated
     */
    int insert(TBaseMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_Menu
     *
     * @mbg.generated
     */
    int insertSelective(TBaseMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_Menu
     *
     * @mbg.generated
     */
    List<TBaseMenu> selectByExample(TBaseMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_Menu
     *
     * @mbg.generated
     */
    TBaseMenu selectByPrimaryKey(Long guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_Menu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TBaseMenu record, @Param("example") TBaseMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_Menu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TBaseMenu record, @Param("example") TBaseMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_Menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TBaseMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_Menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TBaseMenu record);
}