package com.qi.management.mapper;

import com.qi.management.model.domain.TBaseDictionary;
import com.qi.management.model.domain.TBaseDictionaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBaseDictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_Dictionary
     *
     * @mbg.generated
     */
    long countByExample(TBaseDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_Dictionary
     *
     * @mbg.generated
     */
    int deleteByExample(TBaseDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_Dictionary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_Dictionary
     *
     * @mbg.generated
     */
    int insert(TBaseDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_Dictionary
     *
     * @mbg.generated
     */
    int insertSelective(TBaseDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_Dictionary
     *
     * @mbg.generated
     */
    List<TBaseDictionary> selectByExample(TBaseDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_Dictionary
     *
     * @mbg.generated
     */
    TBaseDictionary selectByPrimaryKey(Long guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_Dictionary
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TBaseDictionary record, @Param("example") TBaseDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_Dictionary
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TBaseDictionary record, @Param("example") TBaseDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_Dictionary
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TBaseDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Base_Dictionary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TBaseDictionary record);
}