package com.qi.backstage.management.model.domain;

import com.sfsctech.base.model.BaseDto;

public class BaseButton extends BaseDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_button.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_button.Guid
     *
     * @mbg.generated
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_button.Parent
     *
     * @mbg.generated
     */
    private String parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_button.MenuGuid
     *
     * @mbg.generated
     */
    private String menuguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_button.MenuCode
     *
     * @mbg.generated
     */
    private String menucode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_button.Code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_button.Name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_button.Url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_button.Type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_button.Description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_button.Status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_button.ID
     *
     * @return the value of base_button.ID
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_button.ID
     *
     * @param id the value for base_button.ID
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_button.Guid
     *
     * @return the value of base_button.Guid
     * @mbg.generated
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_button.Guid
     *
     * @param guid the value for base_button.Guid
     * @mbg.generated
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_button.Parent
     *
     * @return the value of base_button.Parent
     * @mbg.generated
     */
    public String getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_button.Parent
     *
     * @param parent the value for base_button.Parent
     * @mbg.generated
     */
    public void setParent(String parent) {
        this.parent = parent == null ? null : parent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_button.MenuGuid
     *
     * @return the value of base_button.MenuGuid
     * @mbg.generated
     */
    public String getMenuguid() {
        return menuguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_button.MenuGuid
     *
     * @param menuguid the value for base_button.MenuGuid
     * @mbg.generated
     */
    public void setMenuguid(String menuguid) {
        this.menuguid = menuguid == null ? null : menuguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_button.MenuCode
     *
     * @return the value of base_button.MenuCode
     * @mbg.generated
     */
    public String getMenucode() {
        return menucode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_button.MenuCode
     *
     * @param menucode the value for base_button.MenuCode
     * @mbg.generated
     */
    public void setMenucode(String menucode) {
        this.menucode = menucode == null ? null : menucode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_button.Code
     *
     * @return the value of base_button.Code
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_button.Code
     *
     * @param code the value for base_button.Code
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_button.Name
     *
     * @return the value of base_button.Name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_button.Name
     *
     * @param name the value for base_button.Name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_button.Url
     *
     * @return the value of base_button.Url
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_button.Url
     *
     * @param url the value for base_button.Url
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_button.Type
     *
     * @return the value of base_button.Type
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_button.Type
     *
     * @param type the value for base_button.Type
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_button.Description
     *
     * @return the value of base_button.Description
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_button.Description
     *
     * @param description the value for base_button.Description
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_button.Status
     *
     * @return the value of base_button.Status
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_button.Status
     *
     * @param status the value for base_button.Status
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}