#server setting
server:
  port: 8101
  address: localhost
  context-path: /sso
  tomcat:
    # 解析含有中文名的文件的url
    uri-encoding: utf-8
    # 最大连接数
    max-connections: 1000
    # 最大线程数，即最大并发数。
    max-threads: 500
    # 最小备用线程数
    min-spare-threads: 20
    # 线程数达到maxThreads后，后续请求会被放入一个等待队列，acceptCount是这个队列的大小
    accept-count: 100
    # tomcat连接器
    connector: org.apache.coyote.http11.Http11NioProtocol
    # tomcat优化
    optimize: true
  session:
    cookie:
      domain: www.zzl.com
      # 只能在服务端设置
      http-only: true
      # 只能在 HTTPS 连接中被传递
#      secure: true
      # cookie保持时间(秒) 30分钟
      max-age: 1800
      path: /
#  context-parameters:
#    logback-config-location: http://localhost:8888/logback/framework/thymeleaf
#    logback-expose-webapp-root: true
#spring mvc setting
spring:
  thymeleaf:
    cache: false
    suffix: .html
  mvc:
    # 指定静态资源处理路径
    static-path-pattern: /static/**
    view:
      suffix: .html
  redis:
    protocol: Single
    single:
      host: 172.16.225.98
      port: 6379
      password: redis123
    pool:
      max-active: 300
      max-wait: 10000
      max-idle: 100
      min-idle: 50
dubbo:
  application:
    #服务消费名称信息
    name: SSO-Website
    #日志适配
    logger: slf4j
  registry:
    #zookeeper注册中心服务地址
    address: zookeeper://172.16.225.98:2181
    #注册中心不存在时，是否报错
    check: false
    #是否向此注册中心注册服务，如果设为false，将只订阅，不注册
    register: true
    #是否向此注册中心订阅服务，如果设为false，将只注册，不订阅
    subscribe: true
    #注册中心请求超时时间(毫秒)
    timeout: 2000
  rpc:
    service-package: com.qi.sso.website.rpc
    concurrency: 40
#common setting
website:
  # 网站支持
  support:
    # 静态资源服务
    static-resources: http://localhost:8080
    welcome-file: /index
  # 单点登录
  sso:
    login-url: http://www.zzl.com/sso/index
    register-url: http://www.zzl.com/sso/register
    forget-url: http://www.zzl.com/sso/forget
    portal-url: http://www.zzl.com/portal/index
    auth:
      protocol: Rpc
      way: Simple
  # 服务架构
  session:
    exclude-path: /index, /login
  security:
    csrf:
      open: true
      intercept-exclude-path:  /logout
      verify-exclude-path: /index
