#server setting
server:
  port: 8101
  address: localhost
  context-path: /sso
  tomcat:
    uri-encoding: utf-8
  session:
    cookie:
      domain: www.zzl.com
      # 只能在服务端设置
      http-only: true
      # 只能在 HTTPS 连接中被传递
#      secure: true
      max-age: 1800
      path: /
#  context-parameters:
#    logback-config-location: http://localhost:8888/logback/framework/thymeleaf
#    logback-expose-webapp-root: true
#spring mvc setting
spring:
  thymeleaf:
    cache: false
    suffix: .html
  mvc:
    # 指定静态资源处理路径
    static-path-pattern: /static/**
    view:
      suffix: .html
  redis:
    protocol: single
    single:
      host: 172.16.225.98
      port: 6379
      password: redis123
    pool:
      max-active: 300
      max-wait: 10000
      max-idle: 100
      min-idle: 50
dubbo:
  application:
    #服务消费名称信息
    name: SSO-Website
    #日志适配
    logger: slf4j
  registry:
    #zookeeper注册中心服务地址
    address: zookeeper://172.16.225.98:2181
    #注册中心不存在时，是否报错
    check: false
    #是否向此注册中心注册服务，如果设为false，将只订阅，不注册
    register: true
    #是否向此注册中心订阅服务，如果设为false，将只注册，不订阅
    subscribe: true
    #注册中心请求超时时间(毫秒)
    timeout: 2000
  rpc:
    service-package: com.qi.sso.website.rpc
#common setting
website:
  # 网站支持
  support:
    # 静态资源服务
    static-resources: http://localhost:8080
    welcome-file: /index
  # 单点登录
  sso:
    register-url: http://www.zzl.com/sso/register
    forget-url: http://www.zzl.com/sso/forget
    portal-url: http://www.zzl.com/portal/index
  # 服务架构
  session:
    exclude-path: /index, /login
  security:
    open-csrf: true
    csrf:
      intercept-exclude-path:  /logout
      verify-exclude-path: /index
