server:
  port: 10002
eureka:
  instance: #如果只是配置了eureka.instance.prefer-ip-address=true，而不配置eureka.instance.instance-id,那还是显示localhost，但ip地址是可以访问得了
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 没有心跳的淘汰时间，10秒，即服务续约到期时间（缺省为90s）
    hostname: ${eureka.instance.ip-address}
    instance-id: ${eureka.instance.ip-address}:${server.port}
    prefer-ip-address: true
    ip-address: localhost
  client:
    register-with-eureka: true #启用自己作为客户端注册，禁用的话spring boot admin就看不到eureka-server的服务了，也就无法检测状态了
    fetch-registry: true #是否需要去检索寻找服务
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
spring:
  boot:
    admin:
      client:
        url: "http://${eureka.instance.ip-address}:10001"
  application:
    name: support-eureka
logging:
  file: "D:/opt/logs/support/${spring.application.name}.log"