server:
  port: 10002
  # logback config service setting
  context-parameters:
    logback-config-location: http://172.16.225.99:8888/logback/logback/framework/website
    logback-expose-webapp-root: true
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
