package com.qi.backstage.mapper;

import com.qi.backstage.model.domain.BaseSystem;
import com.qi.backstage.model.domain.BaseSystemExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface BaseSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_system
     *
     * @mbg.generated
     */
    long countByExample(BaseSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_system
     *
     * @mbg.generated
     */
    int deleteByExample(BaseSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_system
     *
     * @mbg.generated
     */
    int insert(BaseSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_system
     *
     * @mbg.generated
     */
    int insertSelective(BaseSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_system
     *
     * @mbg.generated
     */
    List<BaseSystem> selectByExample(BaseSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_system
     *
     * @mbg.generated
     */
    BaseSystem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_system
     *
     * @mbg.generated
     */
    BaseSystem selectByGuid(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_system
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BaseSystem record, @Param("example") BaseSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_system
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BaseSystem record, @Param("example") BaseSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BaseSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BaseSystem record);
}