#server setting
server:
  port: 8102
  address: localhost
  context-path: /sso-server
  tomcat:
    uri-encoding: utf-8
#  context-parameters:
#    logback-config-location: http://localhost:8888/logback/framework/thymeleaf
#    logback-expose-webapp-root: true
#spring mvc setting
spring:
  redis:
    host-name: 172.16.225.98
    port: 6379
    password: redis123
    pool:
      max-total: 300
      max-wait-millis: 10000
      max-idle: 100
      min-idle: 50
#dubbo setting
dubbo:
  application:
    # 服务提供者名称信息
    name: SSO-Server
    # 日志适配
    logger: slf4j
  registry:
    # zookeeper注册中心服务地址
    address: zookeeper://192.168.100.103:2181
    # 注册中心不存在时，是否报错
    check: true
    # 是否向此注册中心注册服务，如果设为false，将只订阅，不注册
    register: true
    # 是否向此注册中心订阅服务，如果设为false，将只注册，不订阅
    subscribe: true
    # 注册中心请求超时时间(毫秒)
    timeout: 2000
  protocol:
    # 通信协议，默认dubbo
    name: dubbo
    # 协议端口，默认20880
    port: 20880
    # 是否使用kryo序列化
    kryo: true
  rpc:
    service-package: com.qi.sso.server.rpc
#common setting
website:
  jwt:
    subject: Single Sign-on
    issuer: SSO-Server
#    expiration: 1800000
    expiration: 60000