package com.qi.management.mapper;

import com.qi.management.model.domain.BaseDatasource;
import com.qi.management.model.domain.BaseDatasourceExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface BaseDatasourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_datasource
     *
     * @mbg.generated
     */
    long countByExample(BaseDatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_datasource
     *
     * @mbg.generated
     */
    int deleteByExample(BaseDatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_datasource
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_datasource
     *
     * @mbg.generated
     */
    int insert(BaseDatasource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_datasource
     *
     * @mbg.generated
     */
    int insertSelective(BaseDatasource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_datasource
     *
     * @mbg.generated
     */
    List<BaseDatasource> selectByExample(BaseDatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_datasource
     *
     * @mbg.generated
     */
    BaseDatasource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_datasource
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BaseDatasource record, @Param("example") BaseDatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_datasource
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BaseDatasource record, @Param("example") BaseDatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_datasource
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BaseDatasource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_datasource
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BaseDatasource record);
}